# Site settings
title: Christian Walker
email: walkerc3@allegheny.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome! This will serve as my website for the business world.
  Only professional information will be posted here. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  dubswalker

# Build settings
markdown: kramdown
